### ISSUE TITLE
ONT compatibility 

### ISSUE THREAD

**Issue by fcamara7** [ERGA-consortium/EARs#12]
Hi Diego,

Over here at the CNAG, as you know, we currently assemble genomes using ONT technology and I have had a bit of trouble getting your report to work for us. One issue we have is that since we have a "collapsed" assembly merqury only produces three st.png files and your python script is expecting four. 

Thanks for helping us with this when you have time!

-----------------------
Our yaml is below.

# This is the yaml file for generating the ERGA Assembly Report (EAR) using the make_EAR.py script
# Please complete the required information pointed as <Insert ...>
# The file [example]rCarCar2_EAR.yaml contains an example of a completed yaml file

# GENERAL INFORMATION
ToLID: fValHis
Species: Valencia hispanica
Sex: unknown # for example: XX, XY, ZZ, ZW, unknown, NA...
Submitter: Francisco Camara Ferreira
Affiliation: CNAG Barcelona
Tags: ERGA-BGE # valid tags are ERGA-Pilot, ERGA-BGE, ERGA-Satellite

# SEQUENCING DATA
DATA:
      - ONT: 74x
      - Illumina: 83x
      - OmniC: 70x

# GENOME PROFILING DATA
PROFILING:
  GenomeScope:
    version: 2.0
    results_folder: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/s02.2_p01.1_preprocess_illumina_reads/genomescope2_k21
  

# ASSEMBLY PIPELINE
CONTIGGING:
  nextdenovo: 
    version: 2.5.0
    collapsed:
      gfastats--nstar-report_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/s03.2_p02.1_nextdenovo/nextdenovo.assembly.gfastats.txt
      busco_short_summary_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s03.2_p02.1_nextdenovo/busco/nextdenovo.assembly.short_summary.txt
      merqury_folder: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s03.2_p02.1_nextdenovo/merqury/nextdenovo.assembly
  
  hypo: 
    version: 1.0.3
    collapsed:
      gfastats--nstar-report_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/s04.2_p03.2_polishing/hypo/nextdenovo.assembly.hypo1.gfastats.txt
      busco_short_summary_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s04.2_p03.2_polishing/busco/nextdenovo.assembly.hypo1.short_summary.txt
      merqury_folder: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s04.2_p03.2_polishing/merqury/nextdenovo.assembly.hypo1
  
  purge_dups: 
    version: 1.2.6
    collapsed:
      gfastats--nstar-report_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/s05.1_p04.1_run_purgedups/flye.assembly.hypo1.purged.gfastats.txt
      busco_short_summary_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s05.3_p04.2_run_purgedups/busco/nextdenovo.assembly.hypo1.purged.short_summary.txt
      merqury_folder: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/s05.3_p04.2_run_purgedups/merqury/nextdenovo.assembly.hypo1.purged_complete

SCAFFOLDING:
  YaHS: 
    version: 1.2a
    collapsed: 
      gfastats--nstar-report_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/curation/yahs_scaffolding/fValHis_yahs_scaffolds_final.gfastats.txt
      busco_short_summary_txt: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/yahs_scaffolding/busco/fValHis_yahs_scaffolds_final.short_summary.txt
      merqury_folder: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/evaluations/yahs_scaffolding/merqury/fValHis_yahs_scaffolds_final
      pretext_FullMap_png: /scratch_isilon/groups/assembly/data/projects/BGE/fValHis/assembly/curation/hic_remap/out_fValHis_yahs_scaffolds_final/snapshots/three_wave_blue_green_yellow/assembly_mq40.fValHis_yahs_scaffolds_final_FullMap.png

**Comment by diegomics** [comment]
Hi @fcamara7 I just came back. I will look into this ;)

**Comment by diegomics** [comment]
Hi @fcamara7 please check the updated script, let me know if it's working

**Comment by fcamara7** [comment]
Thanks @diegomics !! It seems to work just fine now! I will show it to Tyler tomorrow and I will get back to you if there are any further issues but I think it is fine now. Thanks for acting on this so quickly! :)
