### ISSUE TITLE
Defaults in erga_env.yaml

### ISSUE THREAD

**Issue by DLBPointon** [ERGA-consortium/EARs#122]
Hi all,

Due to the policy changes by Anaconda, we (Sanger at least) are avoiding use of the `defaults` channel. Is it possible to specify `conda-forge` (I've just checked and they do provide these packages) rather than `defaults`.

Thanks
Damon

**Comment by diegomics** [comment]
Hi Damon! Please see #123

**Comment by DLBPointon** [comment]
Hi Diego

Thanks for the quick work, looks great!
